---
metadata:
  name: template-schema
  description: CIC meta-schema — defines the structure for all versioned schema artifacts
  version: null
  license: CC-BY-NC-SA-4.0
  main_branch: main
  owner: Gabor Zoltan Sinko
  tags:
    - schema
    - meta-schema
    - template
compiler_settings:
  repo_type: schema
  component_name: template-schema
  meta_schemas_dir: ./
  meta_schema_file: md.meta.schema.yaml
  source_dir: schemas
  canonical_source_file: schemas/index.yaml
  dependencies_dir: dependencies
  release_dir: release
  vault_key_name: cic-my-sign-key
  cic_root_ca_key_name: cic-root-ca-key
  vault_cert_mount: cic-my-sign-key
  vault_cert_secret_name: crt
  vault_cert_secret_key: bar